name: trishula-genocan-0.1dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - defaults::openjdk=8.0.152
  - r-base=3.4.1
  - r-rmarkdown=1.10
  - fastqc=0.11.8
  - bwa=0.7.17
  - samtools=1.9
  - bcftools=1.9
  - dedup=0.12.3
  - qualimap=2.2.2b
  - multiqc=1.6
  - fastp=0.19.4
  - bamutil=1.0.14
  - libiconv=1.15
  - vcftools=0.1.15

